name: firstworkflow
on: workflow_dispatch
jobs:
  Jpp:
    runs-on: ubuntu-latest
    steps:
     - name: truc1
       run: echo "c'est truc"
     - name: truc2
       run: echo "c'est truc2"
     - name: truc3
       run: echo "c'est fini"
